---
# tasks file for kde-dev

- name: Set variable for kde-dev
  set_fact:
    config_local_path: /home/{{ target_user }}/workspace/dotfiles
    kde_work_dir_path: /home/{{ target_user }}/workspace/kde/src
    kdesrc_build_path: /home/{{ target_user }}/workspace/kde/src/kdesrc-build

- name: Install dependencies
  pacman:
    state: latest
    name: ['cmake', 'dialog', 'phonon-qt5', 'qt5-webkit', 'qt5-script', 'qt5-svg', 'qt5-tools', 'qt5-x11extras', 'enchant', 'jasper', 'openexr', 'libutempter', 
          'docbook-xsl', 'shared-mime-info', 'giflib', 'libxss', 'upower', 'udisks2', 'bzr', 'git', 'doxygen', 'perl-json', 'perl-libwww', 'perl-xml-parser', 'perl-io-socket-ssl', 
          'akonadi', 'xorg-server-devel', 'libpwquality', 'fontforge', 'eigen', 'libfakekey', 'qca-qt5', 'xapian-core', 'xsd', 'gperf', 'perl-yaml-syck', 'intltool', 'kdesdk', 
          'qrencode', 'libdmtx', 'boost', 'ruby-test-unit', 'qt5-base', 'qt5-doc', 'extra-cmake-modules']

- name: Create kde src directory
  file:
    path: "{{ kde_work_dir_path }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"

- name: Check if kdesrc-build directory already present
  stat:
    path: "{{ kde_work_dir_path }}/kdesrc-build"
  register: kde_work_dir_stat

- name: Clone kdesrc-build repo
  git:
    repo: https://invent.kde.org/sdk/kdesrc-build.git
    dest: "{{ kdesrc_build_path }}"
    update: yes
  become_method: runas
  become_user: "{{ target_user }}"
  when: not kde_work_dir_stat.stat.exists

- name: Create symbolic link for the config
  file:
    src: "{{ config_local_path }}/kdesrc/kdesrc-buildrc"
    dest: /home/{{ target_user }}/.kdesrc-buildrc
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    state: link

- name: Create symbolic link for kdesrc-build script
  file:
    src: "{{ kdesrc_build_path }}/kdesrc-build"
    dest: /usr/local/bin/kdesrc-build
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    state: link
...