---
# tasks file for spotify

- name: Set variable
  set_fact:
    config_local_path: /home/{{ target_user }}/workspace/dotfiles
    auracle_work_dir_path: /tmp/auracle
    package_build_path: /tmp/auracle/spotify
    package_name: spotify

- name: Check if spotify is installed
  shell: 
    cmd: which spotify
  register: spotify_path

- name: Download package
  shell:
    cmd: auracle download {{ package_name }}
    chdir: "{{ auracle_work_dir_path }}"
  become_method: runas
  become_user: "{{ target_user }}"
  when: not spotify_path

- name: Build package
  shell: 
    cmd: yes | makepkg -sr
    chdir:  "{{ package_build_path }}"
  become_method: runas
  become_user: "{{ target_user }}"
  when: not spotify_path

- name: Register package name
  shell:
    cmd: ls {{ package_name }}*.tar.xz
    chdir:  "{{ package_build_path }}"
  register: built_package_name
  when: not spotify_path

- name: Install package with pacman
  pacman:
    name: "{{ package_build_path }}/{{ built_package_name.stdout_lines[0] }}"
    state: present
  when: not spotify_path

- name: Copy application config for HiDPI settings
  copy:
    src: spotify.desktop
    dest: /home/{{ target_user }}/.local/share/applications/spotify.desktop
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
...