---
# tasks file for git

- name: Install git
  pacman:
    name: git
    state: latest

- name: Create gitconfig symlink from work dotfiles
  file:
    src: /home/{{ target_user }}/workspace/dotfiles/git/gitconfig
    dest: /home/{{ target_user }}/.gitconfig
    state: link

...
